"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });
import "flowbite/dist/flowbite.css";
import { Providers } from "@/state/provider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import Layout from "@/layout";

// export const metadata = {
//   title: "Feedlio",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <QueryClientProvider client={queryClient}>
          <Providers>
            <Layout>{children}</Layout>
          </Providers>
        </QueryClientProvider>
      </body>
    </html>
  );
}
